# Generated by Django 3.2.8 on 2023-12-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pages',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
