# Generated by Django 3.2.8 on 2023-12-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gym_track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_hours', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('trained_days', models.IntegerField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
